server:
  port: 6061

spring:
  application:
    name: account-service
  cloud:
    stream:
      kafka:
        binder:
          configuration:
            security:
              protocol: SSL
          brokers:
            - kafka1:29093
            - kafka2:29096
            - kafka3:29099
      bindings:
        boughtBook-in:
          destination: boughtBook